### PR TITLE
Demo

### PR DESCRIPTION
**Pull request by lorentzlasson**
adjusted to support bluemix deployment, only need to change host in manifest.yml to prevent url collision

### CODE REVIEW

**Comment by smeets** [comment]
:+1: What do @cblgh, @axelmartensson think?

**Comment by cblgh** [comment]
:100:

**Comment by lorentzlasson** [comment]
currently deployed on http://oh-wow-gaem.mybluemix.net/ in the "nordic iot
hackathon" org, in "smarter transportation" space

2015-04-16 13:38 GMT+02:00 Alexander Cobleigh notifications@github.com:

**Comment by smeets** [comment]
cool! should probably update the README with a list of websites.

do you know for how long it will stay playable on bluemix?

**Comment by lorentzlasson** [comment]
as long as the hackathon organization stays up, which i think will be a while. you always have the option to deploy it to your own organization also. as long as your collected apps uses < 512mb/h (this one run on 128mb/h), it will cost 0

**Pull request merged**
